## list VS ndarray

#### 現在有一個外來一週 Taipei的溫度list(Temperature_Taipei)

In [1]:
Temperature_Taipei = [22 , 24 , 19, 19, 30, 21, 25]

#### Question1. 希望可以將Temperature_Taipei中的所有溫度都轉成華氏

In [2]:
Temperature_Taipei_Fahrenheit = Temperature_Taipei * (9/5) + 32  

TypeError: can't multiply sequence by non-int of type 'float'

#### Answer1.1 使用ndarray

In [3]:
import numpy as np

In [4]:
Temperature_Taipei_array = np.array([22 , 24 , 19, 19, 30, 21, 25])
Temperature_Taipei_Fahrenheit_array = Temperature_Taipei_array * (9/5) + 32
print(Temperature_Taipei_Fahrenheit_array)

[ 71.6  75.2  66.2  66.2  86.   69.8  77. ]


## Loop 

### Loop -- for

#### Question2. 希望一次印出一天的溫度(Temperature_Taipei)

#### Answer2.1 一個一個print

In [5]:
print(Temperature_Taipei[0])
print(Temperature_Taipei[1])
print(Temperature_Taipei[2])
print(Temperature_Taipei[3])
print(Temperature_Taipei[4])
print(Temperature_Taipei[5])
print(Temperature_Taipei[6])

22
24
19
19
30
21
25


#### Answer2.2 利用for

In [6]:
for i in Temperature_Taipei:
    print(i)

22
24
19
19
30
21
25


### [Note] -- string

#### 字串可以相加(+)，不能相減(-)

In [7]:
city = 'Tai' + 'pei'
print(city)

Taipei


In [8]:
'Tai' - 'i'

TypeError: unsupported operand type(s) for -: 'str' and 'str'

#### 字串是字母組成的

In [9]:
city='Taipei'
for i in city:
    print (i)

T
a
i
p
e
i


### [Note] -- range

In [10]:
print(range(10))

range(0, 10)


In [11]:
print(type(range(10)))

<class 'range'>


In [12]:
print(list(range(10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [13]:
print(list(range(0, 10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [14]:
print(list(range(0, 10, 2)))

[0, 2, 4, 6, 8]


In [15]:
print(list(range(1, 6, 2)))

[1, 3, 5]


### Loop -- for 

#### 輸出range(-5,6,-1)中的元素

In [16]:
for i in range(5, -6 , -1):
    print(i)

5
4
3
2
1
0
-1
-2
-3
-4
-5


#### 輸出不必是單一個值也可以是list或dictionary

In [17]:
city = ['Taipei', ['Taichung',22],  {'Kaohsiung':25}]

Method1.

In [18]:
for i in range(len(city)):
    print (city[i])

Taipei
['Taichung', 22]
{'Kaohsiung': 25}


Method2.

In [19]:
city = ['Taipei', ['Taichung',22],  {'Kaohsiung':25}]
for i in city:
    print (i)

Taipei
['Taichung', 22]
{'Kaohsiung': 25}


#### 當sequence 是一個dictionary

In [20]:
weather_dict = { 'Taipei':'rainy', 'Taichung':'cloudy' , 'Tainan':'sunny' , 'Kaohsiung':'sunny' }

In [21]:
print(weather_dict.keys())

dict_keys(['Taichung', 'Taipei', 'Tainan', 'Kaohsiung'])


輸出Key值

In [22]:
for i in weather_dict:
    print(i)

Taichung
Taipei
Tainan
Kaohsiung


輸出Key,Value

In [23]:
for (key, value) in weather_dict.items():
    print(key, ",", value)

Taichung , cloudy
Taipei , rainy
Tainan , sunny
Kaohsiung , sunny


### [Note] -- zip

#### 壓合兩個以上list

長度相同

In [24]:
Week = ['SUN','MON','TUE','WED','THU','FRI','SAT']
Temperature_Taipei = [22 , 24 , 19, 19, 30, 21, 25]

In [25]:
list( zip( Week,Temperature_Taipei ) )

[('SUN', 22),
 ('MON', 24),
 ('TUE', 19),
 ('WED', 19),
 ('THU', 30),
 ('FRI', 21),
 ('SAT', 25)]

長度不同

In [26]:
Week = ['SUN','MON','TUE','WED','THU','FRI','SAT']
Temperature_Taipei = [22 , 24 , 19, 19, 30, 21, 25]
Weather_Taipei = ['Yes','Yes','No']

In [27]:
list( zip( Week,Temperature_Taipei,Weather_Taipei ) )

[('SUN', 22, 'Yes'), ('MON', 24, 'Yes'), ('TUE', 19, 'No')]

#### for , zip

In [28]:
for week ,temperature in zip( Week,Temperature_Taipei ):
    print(week ,temperature)

SUN 22
MON 24
TUE 19
WED 19
THU 30
FRI 21
SAT 25


In [29]:
Temperature_Taipei = [22 , 24 , 19, 19, 30, 21, 25]

In [30]:
Temperature_Taipei[0]

22

### Note -- enumerate

#### 同時取得sequence的索引值及其值

不使用enumerate

In [31]:
for index in range(len(Temperature_Taipei)): 
    print(index , ":", Temperature_Taipei[index])

0 : 22
1 : 24
2 : 19
3 : 19
4 : 30
5 : 21
6 : 25


使用enumerate

In [32]:
for index, temperature in enumerate(Temperature_Taipei): 
    print(index , ":", temperature)

0 : 22
1 : 24
2 : 19
3 : 19
4 : 30
5 : 21
6 : 25


## Exercise

#### Answers1.2 利用for

In [33]:
for i in Temperature_Taipei:
    print(i * (9/5) + 32)

71.6
75.2
66.2
66.2
86.0
69.80000000000001
77.0


將轉成華氏的結果存在一個list中

In [34]:
Temperature_Taipei_Fahrenheit = []
for i in Temperature_Taipei:
    Temperature_Taipei_Fahrenheit.append( i * (9/5) + 32 )
print(Temperature_Taipei_Fahrenheit)

[71.6, 75.2, 66.2, 66.2, 86.0, 69.80000000000001, 77.0]


## Exercise

#### Question3. 利用 for 迴圈，計算 1 加到 100

#### Answers3

In [35]:
sum( range(1,101) )

5050

Method1.

In [36]:
total = 0
for i in range(1,101):
    total = total+i
print(total)    

5050


Method2.

In [37]:
total = 0
for i in range(1,101):
    total +=i
print(total)    

5050


## Exercise

#### Question4. 利用 for 迴圈，計算 5!

#### Answers4

Method1.

In [38]:
print(list(range(1,6)))

[1, 2, 3, 4, 5]


In [39]:
factorial = 1
for i in range(1,6):
    factorial = factorial * i
print(factorial) 

120


Method2.

In [40]:
factorial = 1
for i in range(1,6):
    factorial *= i
print(factorial)   

120


### Loop -- while

#### 利用 while 迴圈，計算 1 加到 100

In [41]:
total = 0
i=0
while i < len(range(1,101)):
    total += range(1,101)[i]
    i += 1
print(total) 

5050


### Loop -- Nested loops

九九乘法

In [42]:
for i in range(1,10):
    for j in range(1,10):
        k=i*j
        print (k , end=' ')
    print()    

1 2 3 4 5 6 7 8 9 
2 4 6 8 10 12 14 16 18 
3 6 9 12 15 18 21 24 27 
4 8 12 16 20 24 28 32 36 
5 10 15 20 25 30 35 40 45 
6 12 18 24 30 36 42 48 54 
7 14 21 28 35 42 49 56 63 
8 16 24 32 40 48 56 64 72 
9 18 27 36 45 54 63 72 81 


## Coditional judgment

#### Question5. 未來一週Taipei溫度，若溫度小於等於22在家否則出門

#### Answer5.

In [43]:
Temperature_Taipei = [22 , 24 , 19, 19, 30, 21, 25]

In [44]:
for i in Temperature_Taipei :
    if i <= 22:
        print('在家')
    else :
        print('出門')

在家
出門
在家
在家
出門
在家
出門


#### 利用zip 比較兩個list 

In [45]:
Temperature_Taipei = [22 , 24 , 19, 19, 30, 21, 25]
Temperature_Taichung = [23 , 22 , 19, 20, 29, 19, 27]

In [46]:
for Taipei, Taichung in zip(Temperature_Taipei, Temperature_Taichung) :
    if Taipei > Taichung :
        print('Taipei 好熱')
    elif Taipei < Taichung :
        print('Taichung 好熱')    
    else :
        print('Taipei Taichung 一家親')

Taichung 好熱
Taipei 好熱
Taipei Taichung 一家親
Taichung 好熱
Taipei 好熱
Taipei 好熱
Taichung 好熱


## Loop II

#### Question6 未來一週Taipei溫度，如果遇到非sunny就立即停止輸出

#### Answer6

In [47]:
Weather_Taipei = ['sunny','sunny','cloudy','sunny','rainy','cloudy','rainy']
for day in Weather_Taipei :
    if day !='sunny':
        break   
    else :
        print(day)

sunny
sunny


## Exercise

#### Question7 未來一週Taipei溫度，找出天氣為sunny的星期

#### Answer7

In [48]:
Week = ['SUN','MON','TUE','WED','THU','FRI','SAT']
Weather_Taipei = ['sunny','sunny','cloudy','sunny','rainy','cloudy','rainy']
for i , j in zip(Week,Weather_Taipei) :
    if j != 'sunny':
        continue 
    else :
        print(i)    

SUN
MON
WED


## Defining a Function

### 圓面積

In [49]:
def Circle_Area(r):
    " 輸入半徑，就會回傳圓面積 "
    import math
    result = math.pi * r * r
    return result

In [50]:
Circle_Area(3)

28.274333882308138

In [51]:
help(Circle_Area)

Help on function Circle_Area in module __main__:

Circle_Area(r)
    輸入半徑，就會回傳圓面積



## Exercise

#### Question 8 定義一個計算個數的函數

#### Answer8.

In [52]:
def my_count( x ):
    ''' 
    輸入：一個想要計算的list
    回傳：該list的個數
    '''
    temp_count = 0
    for i in x :
        temp_count += 1
    return(temp_count)

In [53]:
my_count(range(1,101))

100

#### Nested Function

## Exercise

#### Question9 設計一個計算平均數的程式，並計算未來一週Taipei的平均溫度

#### Answer9.

In [54]:
def my_mean( x ):
    ''' 
    輸入：一個想要計算的list
    回傳：該list的平均數
    '''
    def my_sum( x ):
        "Total"
        temp_total = 0
        for i in x:
            temp_total = temp_total+i
        return temp_total    
    def my_count( x ):
        "Count"
        temp_count = 0
        for i in x :
            temp_count += 1
        return(temp_count)   
    temp_mean = my_sum( x ) / my_count( x )
    return temp_mean

In [55]:
Temperature_Taipei = [22 , 24 , 19, 19, 30, 21, 25]
my_mean(Temperature_Taipei)

22.857142857142858

In [56]:
import numpy as np
Temperature_Taipei_array = np.array(Temperature_Taipei)
np.mean(Temperature_Taipei_array)

22.857142857142858

## Numpy

In [57]:
weather_list = [ 'Taipei' , 18.5 , 'rainy' ]
print(weather_list)

['Taipei', 18.5, 'rainy']


In [58]:
weather_array = np.array(weather_list)
print(weather_array)

['Taipei' '18.5' 'rainy']


#### 1d array

In [59]:
array_1d = np.array( [1,2,3] )
print(array_1d)

[1 2 3]


#### 2d array

In [60]:
array_2d = np.array( [ [1,2,3],
                       [4,5,6],
                       [7,8,9] ])
print(array_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### 3d array

In [61]:
array_3d = np.array( [ [ [1,2,3],
                         [4,5,6],
                         [7,8,9] ],
                       [ [2,4,6],
                         [8,10,12],
                         [14,16,18] ] ] )
print(array_3d)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]]


### Numpy -- Create ndarray

#### np.zeros( x )

In [62]:
np.zeros( (2,3) )

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

#### np.ones( x )

In [63]:
np.ones( (2,3,3) )

array([[[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]])

#### np.empty( x )

In [64]:
np.empty( (2,2) )

array([[ -1.28822975e-231,   2.68677955e+154],
       [  2.16810361e-314,   2.16815581e-314]])

#### np.arange( start , stop , step ) 

In [65]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

#### np.random.random( x )

In [66]:
np.random.random( (2,3) )

array([[ 0.72443247,  0.36221005,  0.83533746],
       [ 0.40411298,  0.50047803,  0.67529553]])

In [67]:
np.random.random( (2,3) ) *10

array([[ 9.0806243 ,  8.06596974,  6.48293555],
       [ 2.60836079,  3.80032424,  7.6752374 ]])

#### np.random.uniform( x )

In [68]:
unifom_distrbution = np.random.uniform(-1,1,25)
print(unifom_distrbution)

[-0.81698849 -0.8092268  -0.21778814 -0.14988895 -0.76743938  0.53346935
 -0.49898179 -0.68490761 -0.8662889   0.3414011  -0.12319443  0.51027538
  0.64600026 -0.35993032 -0.24998152  0.17293374 -0.51264971  0.83017583
  0.20901594  0.20222379 -0.5795027  -0.40734808 -0.54851209 -0.41749703
 -0.53547275]


#### np.random.normal( x )

In [69]:
normal_distrbution = np.random.normal( 0 , 1 , 20 )
print(normal_distrbution)

[ 0.59660114  0.8517208   0.59543032 -0.96529298  0.42384755  2.44902125
  0.92739411  0.72272649  0.57841384  0.69285849  0.16320806  0.97271161
  1.52841018  0.73680356 -0.80331464 -0.19490819 -1.57617853  0.51364171
 -0.59377791  0.08408845]


### Numpy -- index

In [70]:
print(array_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


抓出第二列第二欄的元素

In [71]:
array_2d[1,1]

5

第一列

In [72]:
array_2d[0,:]

array([1, 2, 3])

第三欄

In [73]:
array_2d[:,2]

array([3, 6, 9])

array_2d > 5

In [74]:
array_2d > 5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]], dtype=bool)

array_2d > 5 且 array_2d < 8

In [75]:
array_2d[(array_2d > 5) & (array_2d < 8)]

array([6, 7])

## Exercise

#### Question10. 將剛剛產生的九九乘法表存在一個 2d ndarray 中

#### Answer10.

In [76]:
multiplication = np.empty( (9 , 9) )
for i in range(1,10):
    for j in range(1,10):
        multiplication[i,j]= i*j

IndexError: index 9 is out of bounds for axis 1 with size 9

In [77]:
multiplication = np.empty( (9 , 9) )
for i in range(1,10):
    for j in range(1,10):
        multiplication[(i-1),(j-1)]= i*j

In [78]:
print(multiplication)

[[  1.   2.   3.   4.   5.   6.   7.   8.   9.]
 [  2.   4.   6.   8.  10.  12.  14.  16.  18.]
 [  3.   6.   9.  12.  15.  18.  21.  24.  27.]
 [  4.   8.  12.  16.  20.  24.  28.  32.  36.]
 [  5.  10.  15.  20.  25.  30.  35.  40.  45.]
 [  6.  12.  18.  24.  30.  36.  42.  48.  54.]
 [  7.  14.  21.  28.  35.  42.  49.  56.  63.]
 [  8.  16.  24.  32.  40.  48.  56.  64.  72.]
 [  9.  18.  27.  36.  45.  54.  63.  72.  81.]]


## Homework2 Data

Ref : http://www.cwb.gov.tw/V7/climate/monthlyData/mD.htm

In [79]:
Taipei = {     'FEB' : [17.0,'2017/02/19',27.9,'2017/02/10',10.4] ,
               'JAN' : [8.3,'2017/01/04',27.3,'2017/01/20',12.2] , 
               'DEC' : [20.1,'2016/12/21',30.6,'2016/12/28',12.6] , 
               'NOV' : [22.6,'2016/11/13',32.5,'2016/11/24',17.6] , 
               'OCT' : [27.0,'2016/10/02',35.4,'2016/10/30',21.4] , 
               'SEP' : [27.8,'2016/09/16',35.9,'2016/09/20',23.6] , 
               'AUG' : [30.1,'2016/08/04',37.8,'2016/08/31',24.6] , 
               'JUL' : [30.3,'2016/07/28',38.5,'2016/07/18',23.9] , 
               'JUN' : [29.4,'2016/06/01',38.7,'2016/06/15',24.1] , 
               'MAY' : [27.1,'2016/05/31',37.3,'2016/05/17',19.0] , 
               'APR' : [24.0,'2016/04/23',32.2,'2016/04/18',17.1] , 
               'MAR' : [17.5,'2016/03/5',29.4,'2016/03/28',9.4]                                                                                                        
             }  

Kaohsiung = {  'FEB' : [21.1,'2017/02/22',29.8,'2017/02/10',13.8] ,
               'JAN' : [21.7,'2017/01/08',28.5,'2017/01/26',14.7] , 
               'DEC' : [22.9,'2016/12/05',30.0,'2016/12/16',16.2] , 
               'NOV' : [25.7,'2016/11/19',31.9,'2016/11/27',19.7] , 
               'OCT' : [28.4,'2016/10/21',33.0,'2016/10/10',24.0] , 
               'SEP' : [28.4,'2016/09/12',33.9,'2016/09/15',23.4] , 
               'AUG' : [29.4,'2016/08/02',34.2,'2016/08/30',24.8] , 
               'JUL' : [30.2,'2016/07/04',35.1,'2016/07/10',25.4] , 
               'JUN' : [29.7,'2016/06/27',34.8,'2016/06/11',24.6] , 
               'MAY' : [28.9,'2016/05/27',33.6,'2016/05/11',24.8] , 
               'APR' : [26.9,'2016/04/18',33.0,'2016/04/19',21.8] , 
               'MAR' : [21.6,'2016/03/19',29.7,'2016/03/26',12.8]                                                                                                        
             }